[package]
name = "ustb-wifi-tools"
version = "0.5.0"
description = "A Tauri App that can be used to get information of the USTB Wifi"
authors = ["CakeAL"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-start-dragging", "window-close", "window-maximize", "window-unminimize", "window-show", "window-minimize", "window-hide", "window-unmaximize", "macos-private-api", "http-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.117"
reqwest = "0.12.4"
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.86"
regex = "1.10.4"
scraper = "0.19.0"
chrono = "0.4.38"
mac_address = "1.1.7"
headless_chrome = "1.0.10"
rfd = "0.14.1"
window-vibrancy = "0.4"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-gcc"
