[package]
name = "ustb-wifi-tools"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1.6.7", features = ["shell-open"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
reqwest = "0.12.4"
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.86"
regex = "1.10.4"
scraper = "0.19.0"
# 下面这两个不要更新版本
windows = "0.39.0"
webview2-com = "0.19.1"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
